on:
  pull_request:
  push:
    branches:
    - main
name: Test

env:
  GO_VERSION: 1.21.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test ./...
    - run: go vet ./...

    - name: Check Formatting
      run: |
        set -e
        gofmt -l . > fmt.txt
        xargs -I % echo "::error file=%,line=1,title=gofmt::Unformatted file. Run go fmt % to fix." < fmt.txt
        diff <(echo -n) fmt.txt
