on:
  pull_request:
  push:
    branches:
    - main
name: Test

env:
  GO_VERSION: 1.21.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - uses: actions/checkout@v3

    - run: go test ./...
    - run: go vet ./...

    - run: |
        set -e
        UNFORMATTED=$(gofmt -l .)
        echo $UNFORMATTED
        if [ -n $UNFORMATTED ]; then
          echo $UNFORMATTED | xargs -I % echo "::error file=%,line=1,title=gofmt::Unformatted file. Run go fmt % to fix."
        fi
